# Generated by Django 5.1.7 on 2025-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_subscription_updated_ap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
